// Markdown report generator + download helper.

export function buildReport(profile, userRole, summary, clauses) {
  const date = new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' });
  const riskLabel = { red: '🔴 RED FLAG', caution: '🟡 CAUTION', standard: '🟢 Standard', info: 'ℹ️ Info' };
  let md = `# ClauseLens Report — ${profile.docType}\n\n`;
  md += `**Analyzed for:** ${userRole} · **Date:** ${date}\n\n`;
  md += `> ⚠️ This is an AI reading aid, **not legal advice**. For decisions that matter, consult a qualified lawyer.\n\n`;
  if (summary) {
    md += `## Overall: Grade ${summary.grade}\n\n${summary.verdict}\n\n`;
    if (summary.topConcerns?.length) {
      md += `### Top concerns\n${summary.topConcerns.map((c) => `- ${c}`).join('\n')}\n\n`;
    }
    if (summary.beforeSigning?.length) {
      md += `### Before you sign\n${summary.beforeSigning.map((c) => `- [ ] ${c}`).join('\n')}\n\n`;
    }
  }
  md += `## Clause-by-clause\n\n`;
  for (const c of clauses) {
    if (!c.analysis) continue;
    const a = c.analysis;
    md += `### ${c.index}. ${c.title} — ${riskLabel[a.risk]}\n\n`;
    md += `${a.plainEnglish}\n\n`;
    if (a.isUnusual && a.whyUnusual) md += `**Unusual:** ${a.whyUnusual}\n\n`;
    if (a.negotiationTip) md += `**💬 Ask:** ${a.negotiationTip}\n\n`;
  }
  md += `\n---\nGenerated by ClauseLens — documents are processed in your browser.\n`;
  return md;
}

export function download(filename, content) {
  const blob = new Blob([content], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
